# Generated by Django 6.0.1 on 2026-01-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.TextField(help_text='Description of the action to be taken')),
                ('deadline', models.DateTimeField(help_text='When this task needs to be completed')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder has been sent for this task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(help_text='The email this task was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emails.email')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['deadline'],
                'indexes': [models.Index(fields=['deadline'], name='tasks_task_deadlin_736196_idx'), models.Index(fields=['reminder_sent', 'deadline'], name='tasks_task_reminde_d088de_idx')],
            },
        ),
    ]
