# Generated by Django 6.0.1 on 2026-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_attachment'),
        ('tasks', '0003_setup_periodic_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'deadline', '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this task has been marked as completed'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed', 'deadline'], name='tasks_task_is_comp_6474e1_idx'),
        ),
    ]
