# Generated by Django 6.0.1 on 2026-01-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('sender', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('body', models.TextField(help_text='Full email body content')),
                ('received_at', models.DateTimeField(help_text='When the email was received')),
                ('category', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('OPPORTUNITY', 'Opportunity'), ('INFO', 'Information'), ('JUNK', 'Junk')], help_text='ML-classified category of the email', max_length=20, null=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the email content', null=True)),
                ('extracted_deadline', models.DateTimeField(blank=True, help_text='NLP-extracted deadline from email content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(help_text='The mailbox this email belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailboxes.mailbox')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='emails_emai_receive_560f87_idx'), models.Index(fields=['mailbox', '-received_at'], name='emails_emai_mailbox_abba05_idx'), models.Index(fields=['category'], name='emails_emai_categor_e46084_idx')],
            },
        ),
    ]
