# Generated by Django 6.0.1 on 2026-03-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField(help_text='Size in bytes')),
                ('file', models.FileField(blank=True, help_text='Actual file storage (if enabled)', null=True, upload_to='attachments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(help_text='The email this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email')),
            ],
        ),
    ]
