# Generated by Django 6.0.1 on 2026-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='snippet',
            field=models.CharField(blank=True, help_text='Plain text snippet for list views', max_length=500, null=True),
        ),
    ]
