# Generated by Django 6.0.1 on 2026-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail'), ('OUTLOOK', 'Outlook'), ('YAHOO', 'Yahoo'), ('IMAP', 'Generic IMAP'), ('OTHER', 'Other')], help_text='Email service provider', max_length=20)),
                ('email_address', models.EmailField(help_text='Email address of the mailbox', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mailbox is actively being monitored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mailbox',
                'verbose_name_plural': 'Mailboxes',
                'ordering': ['-created_at'],
            },
        ),
    ]
