# Generated by Django 6.0.1 on 2026-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this mailbox was last synced', null=True),
        ),
    ]
