# Generated by Django 6.0.1 on 2026-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_mailbox_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='imap_port',
            field=models.IntegerField(default=993, help_text='IMAP server port (usually 993 for SSL)'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='imap_server',
            field=models.CharField(blank=True, help_text='IMAP server address (e.g., imap.gmail.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='password',
            field=models.CharField(blank=True, help_text='App Password or account password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Whether to use SSL for the connection'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='username',
            field=models.CharField(blank=True, help_text='Username for IMAP login (defaults to email_address if empty)', max_length=255, null=True),
        ),
    ]
