# Generated by Django 6.0.1 on 2026-02-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_mailbox_imap_port_mailbox_imap_server_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this mailbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
